### ISSUE TITLE
Prop Names

### ISSUE THREAD

**Issue by Dan-Wood** [jamesmoriarty/react-instagram-authless-feed#1]
Prop names should be camel case?

className
classNameLoading

**Comment by jamesmoriarty** [comment]
Sure. I'll try push up a new version tonight. I'll change userName too to be consistent.

**Comment by jamesmoriarty** [comment]
Props now camelcase and match convention: https://github.com/jamesmoriarty/react-instagram-authless-feed/commit/25c5a1413294f8bb8a78ace4e80e80b03da6ce64

I've released v1.0.2 with this.
