### ISSUE TITLE
Is there a way we can limit number of photos by passing props?

### ISSUE THREAD

**Issue by jyounosugar** [jamesmoriarty/react-instagram-authless-feed#10]
Want to limit the number of photos. Any number of photos we want.

**Comment by jamesmoriarty** [comment]
I can add it for sure. The max will be limted to 12. This is a limitation on the way it tokenless-ly fetches the data.

**Comment by jamesmoriarty** [comment]
@jyounosugar is this what you had in mind? 

https://github.com/jamesmoriarty/react-instagram-authless-feed/pull/11/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R29

**Comment by jamesmoriarty** [comment]
Added in v1.1.1
