### ISSUE TITLE
Rate limit issues with Instagram (VPN/SSR/Dev)

### ISSUE THREAD

**Issue by arbiasgjoshi** [jamesmoriarty/react-instagram-authless-feed#12]
The repo has been throwing these errors in the past couple of days: 

![Screenshot 2020-10-19 at 01 24 01](https://user-images.githubusercontent.com/24274793/96388535-cb20c600-11a9-11eb-9ff1-fc8de4c18cf8.png)

**Comment by jamesmoriarty** [comment]
@arbiasgjoshi is this the link you are using?

https://www.jamesmoriarty.xyz/react-instagram-authless-feed/

**Comment by jamesmoriarty** [comment]
![Screenshot 2020-10-19 185101](https://user-images.githubusercontent.com/96487/96416836-4632bc80-123c-11eb-82b6-f34d07c973aa.png)

You will need to provide more details.

**Comment by bilaltirmizi123** [comment]
@arbiasgjoshi It was not even working for me at first but then I turned off my VPN and its working fine now.

**Comment by arbiasgjoshi** [comment]
@jamesmoriarty - What type of details do you need? My setup was pretty simple to be honest, simply added this tag: 

```
import Feed from "react-instagram-authless-feed";

<Feed
    userName="-user-name-here-"
    className="image-wrapper"
    classNameLoading="Loading"
/>
```
Also, my screenshot above, is from your own hosted domain, even there I'm getting that error! 

EDIT: I also tried with different VPN to see if the issue is due to Geolocation, but the same error kept happening for me!

**Comment by arbiasgjoshi** [comment]
Not sure if this will work, but this is also what I'm getting as the network response:

![response-delivered](https://user-images.githubusercontent.com/24274793/96581012-741a0e80-12d9-11eb-96f8-9a7ee544f037.png)

Is the HTTP 302 response work as intended here?

**Comment by jamesmoriarty** [comment]
I'll add some error handing around this and an error boundary to the example. Looks like you are triggering a rate limit on the instagram side and its trying to force you to auth your session.

Appears to be a frequent issue when on VPN with shared source/origin IPs.

**Comment by jamesmoriarty** [comment]
@arbiasgjoshi I've added some more error handling in this PR: https://github.com/jamesmoriarty/react-instagram-authless-feed/pull/13

I've redeployed https://www.jamesmoriarty.xyz/react-instagram-authless-feed/ with an error boundary.

**Comment by arbiasgjoshi** [comment]
I have only one question with this new error handling you added! Are you assuming I'm using VPN? 

The issue happened without VPN. I tested with VPN only due to the comment above implying that it works!

**Comment by MichaelZaporozhets** [comment]
I'm hitting this issue as well. Can we look at a more graceful degradation model? currently crashes the page.

**Comment by jamesmoriarty** [comment]
Hey @MichaelZaporozhets, because the rate limit is enforced on Instagram's side its hard to predict. I've changed the functionality to bubble up an exception so it can be handled with an error boundary. The point being the component isn't opinionated in how you should handle this failure. 

See https://github.com/jamesmoriarty/react-instagram-authless-feed/blob/master/src/index.js#L37 and https://reactjs.org/docs/error-boundaries.html

**Comment by jamesmoriarty** [comment]
Because the rate limit is enforced on instagrams side its hard to predict.
Ive changed the functionality to bubble up the exception so it can be
handled with an error boundary. You can see examples of this in the tests
and example app.

**Comment by hvma411** [comment]
Hi, does anybody know what is the rate limit of IG? I mean this requests to get IG posts with this Feed component. @jamesmoriarty error boundary works perfect - thanks for that!

**Comment by mastir** [comment]
Same here, works in test env but after a day in production it fails.

**Comment by jamesmoriarty** [comment]
@mastir are you rendering serverside or anything obliviously different from the examples?

**Comment by mastir** [comment]
@jamesmoriarty Oh, thanks. No, we do not use server side rendering. You should write in **BOLD CAPS** about it, its like <5% of React widgets are targeted for server side usage, i`m sure most of people here simple did import your widget into front end projects and will see rate limits problem soon.

p.s. same trouble with demo
![Screenshot from 2021-01-28 16-29-32](https://user-images.githubusercontent.com/2648333/106152421-1756ab80-6186-11eb-87e8-007d290d46b4.png)

**Comment by jamesmoriarty** [comment]
@mastir appreciate the feedback. I had never seen the rate limit kick in until it was reported here.

I've managed to reproduce it but refreshing the feed maybe x100/ hour from an Australian public IP range and it appears to redirect to the auth/login page for ~24-48 hours.

I'll think about how to better communicate:

<img width="939" alt="Screen Shot 2021-01-29 at 10 02 58 am" src="https://user-images.githubusercontent.com/96487/106209505-3e11f200-6219-11eb-8194-70f6d82956c4.png">

cc/ @hvma411

**Comment by jamesmoriarty** [comment]
Just an FYI for anyone watching this thread: upgrade to v2.0.0 because instagram.com introduced CORs breaking most/all unofficial feed libraries and requires an additional workaround.

**Comment by jamesmoriarty** [comment]
This change fixes this and introduces a new challenge: https://github.com/jamesmoriarty/react-instagram-authless-feed/issues/19
