### ISSUE TITLE
Cannot map media array error (Rate Limit)

### ISSUE THREAD

**Issue by andrenm** [jamesmoriarty/react-instagram-authless-feed#15]
Hi, about 1h ago your component stop working. I'm receiving this error on my console, did something happened?

![image](https://user-images.githubusercontent.com/5672436/100007692-b9e06000-2dcc-11eb-9f2c-6f07c20111d7.png)

It enters on catch block when it tries to assign the [**edges**] variable, in this line:

![image](https://user-images.githubusercontent.com/5672436/100008082-43902d80-2dcd-11eb-88ac-f29ffe9b271b.png)

![image](https://user-images.githubusercontent.com/5672436/100007881-02981900-2dcd-11eb-94bc-083c4937b6cd.png)

**Comment by jamesmoriarty** [comment]
Hey @andrenm, you dont happen to be using a VPN or a private Instagram profile? I've seen this happen when a origin IP hits a rate limit on the Instagram servers. You may be able to trigger it in development if you make enough requests.

I'll try work out a way to raise more specific exceptions.

**Comment by andrenm** [comment]
Hi @jamesmoriarty , I don't use VPN and I'm trying to load a public Instagram account, it's a company account. 

I'm however refreshing the page a lot during front-end development.  You know if this request limitation resets daily? Because it's the first time that this happens to me. I also tried to load my page from another computer, that's connected to the same wifi but it doesn't work either.

Thanks for your help.

Edit: I just opened the developer's tools on my Instagram account and I found this error. Do you think that there's something to do with the request limit? I imagine that Instagram knows that because of my I.P?

![image](https://user-images.githubusercontent.com/5672436/100020140-9e328500-2ddf-11eb-95e6-c0206ab8ca7c.png)

**Comment by jamesmoriarty** [comment]
Hey @andrenm, even if you use a different device (private IP) on the same network you likely have the same public IP and trigger the rate limit. What you are seeing could be symptomatic of the rate limit being trigger. It's hard for me to know exactly because it is on the Instagram side. I thought it would only stay in place for one hour but it doesn't appear to be the case for you.

**Comment by jamesmoriarty** [comment]
Closing for https://github.com/jamesmoriarty/react-instagram-authless-feed/issues/12
