### ISSUE TITLE
Return a map of <Media />

### ISSUE THREAD

**Issue by Dan-Wood** [jamesmoriarty/react-instagram-authless-feed#2]
Is it possible to just return a map() of <Media /> instead of a wrapping <div> ?

`      <div className={classname}>
        {this.state.media.map((media, index) => (
          <Media key={index} src={media.src} url={media.url} alt={media.alt} />
        ))}
      </div>
`

To

`
        {this.state.media.map((media, index) => (
          <Media key={index} src={media.src} url={media.url} alt={media.alt} classname={classname} />
        ))}
`

It gives the user more control over the wrapping elements. Where I was to set each <Media>'s class to "col-6 col-lg-4" (Bootstrap) wrapping it in a <Row>

**Comment by jamesmoriarty** [comment]
In React you need to return a single root element so I don't expect to be able to do that.

If you include the markup you want to wrap it in I can have a think about how to make it configureable. e.g.
```
<row>
  <Media>
  <Media>
  <Media>
</row>
<row>
  <Media>
  ...
```

Alternatively you could use `Instagram.getFeed(username) # => [<MediaObject>]` Reference: https://github.com/jamesmoriarty/react-instagram-authless-feed/blob/master/src/lib/Instagram.js
