### ISSUE TITLE
Errors should be handled by error boundary

### ISSUE THREAD

**Issue by jamesmoriarty** [jamesmoriarty/react-instagram-authless-feed#5]
Remove:

```
.catch(() => this.setState({ loading: false, media: [] }));
```

Add docs.

Usage with: https://reactjs.org/docs/error-boundaries.html

**Comment by juanchoperezj** [comment]
Hi @jamesmoriarty, can I work on this? I haven't work yet with error boundaries, so I think this will be a perfect start on this for me.

**Comment by jamesmoriarty** [comment]
Yep. It's its mainly to remove code and doument how you could use them for
this compoment.
